### ISSUE TITLE
bugyou 0.2.1 doesn't work

### ISSUE THREAD

**Issue by puiterwijk** [sayanchowdhury/bugyou#2]
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: Traceback (most recent call last):
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 191, in _work
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: self.consume(message)
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: File "/usr/lib/python2.7/site-packages/bugyou/consumer.py", line 115, in consume
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: self.served_topic = self.arbiter['served_topic']
Apr 13 23:54:48 bugyou01.phx2.fedoraproject.org fedmsg-hub[10253]: AttributeError: 'BugyouConsumer' object has no attribute 'arbiter'

**Comment by sayanchowdhury** [comment]
This issue has been fixed in prod.

**Comment by sayanchowdhury** [comment]
And the fix has been added in bugyou 0.2.2
